### ISSUE TITLE
[Feature request] documentation

### ISSUE THREAD

**Issue by kookma** [sukima/tiddlywiki-reveal-js#1]
Many thanks for this wonderful plugin. It would be very useful if you can add some more details on widgets, their parameters and themes of reveal.js plugin

**Comment by sukima** [comment]
All the properties they support are documented at Reveal.js. Wouldn't seem redundant to reproduce the same docs here and then worry about maintaining them as things change?

**Comment by sukima** [comment]
How can I make it clearer that the widgets (and their attributes) are a proxy to Reveal.js?

**Comment by kookma** [comment]
Well the document can be improved by describing few of most important parameters. You did this for some of these parameters. I think not all of Tiddlywiki users are coder and can manage by themselves to read Reveal.js docs and use with Tiddlywiki-Reveal.js. Themes, slide numbering, possible jump to a specified slide, ... worth to be a little explained.

I have started making presentation and I can then write more on this.
Please announce tiddlywiki-reveal-js on TW Google forum! I am sure you will get good feedback.

**Comment by kookma** [comment]
I think this can be closed.
