### ISSUE TITLE
[Question] Use with Reveal.js 5.1.0

### ISSUE THREAD

**Issue by kookma** [sukima/tiddlywiki-reveal-js#10]
I followed the instructions for using tiddlywiki-reveal-js under Node.JS. I used the latest reveal.js 5.1 from https://github.com/hakimel/reveal.js/releases/tag/5.1.0

The demo works. I wish to know is this enough to package the tiddlywiki-reveal-js with latest release of reveal.js 5.1?

I am going to use new features like scrollview.

**Comment by sukima** [comment]
I presume it works.

**Comment by kookma** [comment]
Thank you!
