### ISSUE TITLE
How to edit an slide and see it in presentation mode

### ISSUE THREAD

**Issue by kookma** [sukima/tiddlywiki-reveal-js#6]
Assume you are playing a presentation and suddenly you realize you should  correct a slide:

1. from presentation how one can find the tiddler of that slide? I means there is no direct way to open that tiddler to edit.
2. when editing a tiddler say tiddler corresponds to slide 10, after editing/saving you see the presentation has been reset and returned to the first slide. Is there any way to preview a slide (tiddler) in presentation mode while editing?

**Comment by sukima** [comment]
I am not sure how to make Reveal.js be TiddlyWiki aware. This is really a thin layer over Reveal.js embeded feature set.

**Comment by kookma** [comment]
@sukima - thanks for clarification.
