### ISSUE TITLE
Esc key and slide overview in full screen

### ISSUE THREAD

**Issue by kookma** [sukima/tiddlywiki-reveal-js#7]
Assume you are in full screen mode and presenting slides, then you want to go to slide overview and select a certain slide!
What tiddlywiki-reveal.js does is to exit full screen, then you have to press Esc key again to go to slide overview!

Desired action is to have slide overview in fullscreen presentation mode!

**Comment by sukima** [comment]
That sounds like a Reveal.js bug.
